### ISSUE TITLE
There is trixie inside bookworm image

### ISSUE THREAD

**Issue by vladkozlov69** [inindev/nanopc-t6#1]
Hello,

first of all, thanks for the great work.

I downloaded https://github.com/inindev/nanopc-t6/releases/download/v12.0.1/nanopc-t6_bookworm-1201.img.xz using wget and flashed it to NVME using BalenaEtcher. However when I did apt update, it fetches trixie repos.

**Comment by inindev** [comment]
I ended up moving to trixie as the image is based off the 6.6 series kernel.  I should at least delete (or rename) the image that is incorrectly labeled.  I am wondering if I should build both bookworm and trixie images.  Would you like to see a bookworm image?

**Comment by inindev** [comment]
Thank you for reporting this, I have deleted the erroneous image.  Let me know if a bookworm image would be useful and I can publish one.
