### ISSUE TITLE
How to switch to cgroups v1?

### ISSUE THREAD

**Issue by oddfrost** [inindev/nanopc-t6#10]
Hello
I'm trying to install home assistant supervised using your build, but it requeres cgroups v1
It is shown that it is exists, but how can i switch to cgroups v1?

```
grep cgroup /proc/filesystems
nodev   cgroup
nodev   cgroup2
```

In home assistant supervised installer log:

> [warn] Could not find /etc/default/grub or /boot/firmware/cmdline.txt failed to switch to cgroup v1

Any help appreciated.

**Comment by inindev** [comment]
The boot does not use grub, so I expect that is what is actually failing.  I would think there is a tutorial somewhere on how to add grub to a u-boot boot.
