### ISSUE TITLE
What chooses the dtb-file? (T6 vs T6-LTS)

### ISSUE THREAD

**Issue by hreuver0183** [inindev/nanopc-t6#14]
Hi again,
I have been using the T6 for a while now and it is still running great.
I could use your advise on a tiny issue, without a strict deadline.

When I upgraded the 6.11.0 kernel to 6.11.3 the USB2 ports did not work anymore. As you'd guess the rk3588-nanopc-t6.dtb was loaded instead of the rk3588-nanopc-t6-lts. I needed to copy the t6-lts-dtb to the t6-dtb as a quick fix, but I should eventually solve the problem.
(Of course I could also use the kernel you provided, but for me providing my own kernel is part of the fun.)

Now my questions:
What chooses which dtb to load?
More specific, do I  need to change u-boot to load the correct dtb?

If I am correct I might have to ask kwiboo if he could add the t6-lts to his u-boot-rockchip sources.

**Comment by inindev** [comment]
The usb ports on the nanopc-t6 have never worked in upstream builds.  They reason they have worked is that I have written patches to make them work:

https://raw.githubusercontent.com/inindev/linux-rockchip/1ba7ecab866ff7783fe0384af5379cc450a8ed66/patches/04_inindev/0007-arm64-dts-rockchip-enable-usbc-on-the-nanopc-t6.patch

I was optimistic when I saw this upstream PR:

https://patchwork.kernel.org/project/linux-rockchip/patch/20240822-friendlyelec-nanopc-t6-lts-v4-7-892aebcec0c6@linaro.org/

While it is much closer to working, I again found I needed to write patches to make it work:

https://raw.githubusercontent.com/inindev/linux-rockchip/refs/heads/main/patches/03_inindev/0002-arm64-dts-rockchip-add-usbc-port-to-the-nanopc-t6.patch

I really need to submit a PR upstream to fix this.

In the mean time, just link to the working 6.11.0 dtb in the ```/boot``` directory.

The logic of copying the dtb file when a new kernel is installed can be found in the ```/etc/kernel/postinst.d/dtb_cp``` file.

**Comment by hreuver0183** [comment]
The 2310 has a few different devices from the 2301. The LTE-connection is missing, instead there are some extra USB2 connectors. Since my keyboard is usually connected via those I do need to load a different dtb-file from the T6/2301.

If I am correct my 2310 is recognized as a 2301 and thus the rk3588-nanopc-t6.dtb is loaded. I can easily patch the dtb, but the better way is to load the rk3588-nanopc-t6-lts.dtb instead. Right now I was just wondering if I need to look in the kernel for the correct identification or in u-boot, since for the R6C and R6S there are different configurations in u-boot.

**Comment by inindev** [comment]
What you will see ```rk3588-nanopc-t6-lts.dtb``` in the future when the support is part of the mainline. Check here: https://git.kernel.org/pub/scm/linux/kernel/git/mmind/linux-rockchip.git/tree/arch/arm64/boot/dts/rockchip?h=for-next

I have not tested the lts variant yet, but the usb-c support for the non-lts variant not working for me in this tree yet. It may be helpful to compare notes with marcin.juszkiewicz@linaro.org and feel free to show him my patch that makes it work from me: https://raw.githubusercontent.com/inindev/linux-rockchip/refs/heads/main/patches/03_inindev/0002-arm64-dts-rockchip-add-usbc-port-to-the-nanopc-t6.patch

It is possible I am just doing something wrong or not including some other binary update. I hope to get around to testing this more sometime in November.

**Comment by inindev** [comment]
You can get the latest patched one from the linux deb I compiled last week:

```
mkdir temp
cd temp
wget https://github.com/inindev/linux-rockchip/releases/download/v6.11.2/linux-image-6.11.2-1-arm64_6.11.2-1_arm64.deb
ar x linux-image-6.11.2-1-arm64_6.11.2-1_arm64.deb
tar xavf data.tar.xz
cp usr/lib/linux-image-6.11.2-1-arm64/rockchip/rk3588-nanopc-t6-lts.dtb .
```

note that ```ar``` is part of the ```binutils``` package if you do not have it installed

if you want that dtb to load at boot, edit the ```/boot/extlinux/extlinux.conf``` file

files that reference this dtb which would also need to be edited:
```
/boot/extlinux/extlinux.conf
/boot/mk_extlinux
/etc/kernel/postinst.d/dtb_cp
/etc/kernel/postrm.d/dtb_rm
```

**Comment by hreuver0183** [comment]
It might seem trivial,  but this really helps.
It saves me experimenting.

**Comment by hreuver0183** [comment]
Just for the record (from a short email contact with Marcin):
> I bought NanoPC-T6 to have a device to play with firmware rather than
> with Linux. Then it turned out that I got LTS version which needed DT
> changes. So I did them, got them into mainline and went back to other
> duties.
..
> I do have monitor attached to the board but switched off most of time.
> Unless I use EDK2 firmware which enables some minimal graphics support
> to have EFI setup, EFI shell visible. Most of time I use serial console
> or ssh over network.

I conclude he mostly uses his T6 LTS "remote", with a monitor attached for debugging(if any). 
Perhaps he might enable and use some ports for testing, but I hardly would expect him to apply patches outside his targets.

BTW, I mostly use my USB3 connections as "just another USB2 port". No high speed network, storage or monitor.
