### ISSUE TITLE
can this be flashed into emmc with usb?

### ISSUE THREAD

**Issue by lygstate** [inindev/nanopc-t6#6]

**Comment by inindev** [comment]
I just use this simple process to flash emmc and have never tested USB:

```
wget https://github.com/inindev/debian-image/releases/download/v12.4/nanopi-r6c_bookworm-12.4.img.xz
sudo su
xzcat nanopi-r6c_bookworm-12.4.img.xz > /dev/mmcblk0
sync
```

If usb flashing works, please report back here your steps so other people can benefit from your experience.

**Comment by lygstate** [comment]
> I just use this simple process to flash emmc and have never tested USB:
> 
> ```
> wget https://github.com/inindev/debian-image/releases/download/v12.4/nanopi-r6c_bookworm-12.4.img.xz
> sudo su
> xzcat nanopi-r6c_bookworm-12.4.img.xz > /dev/mmcblk0
> sync
> ```
> 
> If usb flashing works, please report back here your steps so other people can benefit from your experience.

Do you means boot with TF first?

**Comment by lygstate** [comment]
> I just use this simple process to flash emmc and have never tested USB:
> 
> ```
> wget https://github.com/inindev/debian-image/releases/download/v12.4/nanopi-r6c_bookworm-12.4.img.xz
> sudo su
> xzcat nanopi-r6c_bookworm-12.4.img.xz > /dev/mmcblk0
> sync
> ```
> 
> If usb flashing works, please report back here your steps so other people can benefit from your experience.

OK, on my system boot into sd card, then flash into `/dev/mmcblk2`
