### ISSUE TITLE
Sync patches to 6.9-rc/6.10 and enable GPU node

### ISSUE THREAD

**Issue by nyanmisaka** [inindev/nanopc-t6#9]
Thank you for your work on this project and tutorials!
Can you sync patches to 6.9-rc/6.10 and add the GPU patch to enable panthor driver for nanopc-t6?

https://git.kernel.org/pub/scm/linux/kernel/git/mmind/linux-rockchip.git/log/?h=for-next
https://gitlab.collabora.com/hardware-enablement/rockchip-3588/linux/-/commits/rk3588/?ref_type=HEADS

**Comment by inindev** [comment]
yes, I am way overdue for an update -- will get one out sometime this month
I have not documented this well, but I ended up combining my numerous ARM repos into one.  The most current nanopc-t6 build is here: https://github.com/inindev/debian-image/releases

**Comment by inindev** [comment]
The latest kernel has the usb-c port and sound working on the nanopc-t6. Everything should now work the best it can at the moment (as far as I know).

**debian bookworm v12.5 arm64 - rc4**
https://github.com/inindev/debian-image/releases

**linux kernel v6.9.3-2 arm64 inindev**
https://github.com/inindev/linux-rockchip/releases

**u-boot arm64 inindev v2024.07-rc4**
https://github.com/inindev/uboot-rockchip/releases

**Comment by nyanmisaka** [comment]
> The latest kernel has the usb-c port and sound working on the nanopc-t6. Everything should now work the best it can at the moment (as far as I know).
> 
> **debian bookworm v12.5 arm64 - rc4** https://github.com/inindev/debian-image/releases
> 
> **linux kernel v6.9.3-2 arm64 inindev** https://github.com/inindev/linux-rockchip/releases
> 
> **u-boot arm64 inindev v2024.07-rc4** https://github.com/inindev/uboot-rockchip/releases

Thanks a lot!
